import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/presentation/components/Navbar";
import GraphQLProvider from "@/presentation/components/GraphQLProvider";
import Footer from "@/presentation/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Conference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <GraphQLProvider>{children}</GraphQLProvider>
        <Footer />
      </body>
    </html>
  );
}
